package com.example.design_engine.layer4_ui

import android.content.Context
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.example.design_engine.layer3_logic.DesignEngineController

object DesignEngineUI {

    // --- BACKGROUND ---
    val ebackground: Color @Composable get() = DesignEngineController.ebackground(isSystemInDarkTheme())
    val ebackgroundLight: Color @Composable get() = DesignEngineController.ebackgroundLight()
    val ebackgroundDark: Color @Composable get() = DesignEngineController.ebackgroundDark()
    val efbackground: Color @Composable get() = DesignEngineController.efbackground(isSystemInDarkTheme())
    val efbackgroundLight: Color @Composable get() = DesignEngineController.efbackgroundLight()
    val efbackgroundDark: Color @Composable get() = DesignEngineController.efbackgroundDark()
    @Composable fun ewbackground(context: Context): Color = DesignEngineController.ewbackground(context, isSystemInDarkTheme())
    @Composable fun ewbackgroundLight(context: Context): Color = DesignEngineController.ewbackgroundLight(context)
    @Composable fun ewbackgroundDark(context: Context): Color = DesignEngineController.ewbackgroundDark(context)

    // --- ON BACKGROUND ---
    val eonbackground: Color @Composable get() = DesignEngineController.eonbackground(isSystemInDarkTheme())
    val eonbackgroundLight: Color @Composable get() = DesignEngineController.eonbackgroundLight()
    val eonbackgroundDark: Color @Composable get() = DesignEngineController.eonbackgroundDark()
    val efonbackground: Color @Composable get() = DesignEngineController.efonbackground(isSystemInDarkTheme())
    val efonbackgroundLight: Color @Composable get() = DesignEngineController.efonbackgroundLight()
    val efonbackgroundDark: Color @Composable get() = DesignEngineController.efonbackgroundDark()
    @Composable fun ewonbackground(context: Context): Color = DesignEngineController.ewonbackground(context, isSystemInDarkTheme())
    @Composable fun ewonbackgroundLight(context: Context): Color = DesignEngineController.ewonbackgroundLight(context)
    @Composable fun ewonbackgroundDark(context: Context): Color = DesignEngineController.ewonbackgroundDark(context)

    // --- SURFACE ---
    val esurface: Color @Composable get() = DesignEngineController.esurface(isSystemInDarkTheme())
    val esurfaceLight: Color @Composable get() = DesignEngineController.esurfaceLight()
    val esurfaceDark: Color @Composable get() = DesignEngineController.esurfaceDark()
    val efsurface: Color @Composable get() = DesignEngineController.efsurface(isSystemInDarkTheme())
    val efsurfaceLight: Color @Composable get() = DesignEngineController.efsurfaceLight()
    val efsurfaceDark: Color @Composable get() = DesignEngineController.efsurfaceDark()
    @Composable fun ewsurface(context: Context): Color = DesignEngineController.ewsurface(context, isSystemInDarkTheme())
    @Composable fun ewsurfaceLight(context: Context): Color = DesignEngineController.ewsurfaceLight(context)
    @Composable fun ewsurfaceDark(context: Context): Color = DesignEngineController.ewsurfaceDark(context)

    // --- ON SURFACE ---
    val eonsurface: Color @Composable get() = DesignEngineController.eonsurface(isSystemInDarkTheme())
    val eonsurfaceLight: Color @Composable get() = DesignEngineController.eonsurfaceLight()
    val eonsurfaceDark: Color @Composable get() = DesignEngineController.eonsurfaceDark()
    val efonsurface: Color @Composable get() = DesignEngineController.efonsurface(isSystemInDarkTheme())
    val efonsurfaceLight: Color @Composable get() = DesignEngineController.efonsurfaceLight()
    val efonsurfaceDark: Color @Composable get() = DesignEngineController.efonsurfaceDark()
    @Composable fun ewonsurface(context: Context): Color = DesignEngineController.ewonsurface(context, isSystemInDarkTheme())
    @Composable fun ewonsurfaceLight(context: Context): Color = DesignEngineController.ewonsurfaceLight(context)
    @Composable fun ewonsurfaceDark(context: Context): Color = DesignEngineController.ewonsurfaceDark(context)

    // --- SURFACE VARIANT ---
    val esurfacevariant: Color @Composable get() = DesignEngineController.esurfacevariant(isSystemInDarkTheme())
    val esurfacevariantLight: Color @Composable get() = DesignEngineController.esurfacevariantLight()
    val esurfacevariantDark: Color @Composable get() = DesignEngineController.esurfacevariantDark()
    val efsurfacevariant: Color @Composable get() = DesignEngineController.efsurfacevariant(isSystemInDarkTheme())
    val efsurfacevariantLight: Color @Composable get() = DesignEngineController.efsurfacevariantLight()
    val efsurfacevariantDark: Color @Composable get() = DesignEngineController.efsurfacevariantDark()
    @Composable fun ewsurfacevariant(context: Context): Color = DesignEngineController.ewsurfacevariant(context, isSystemInDarkTheme())
    @Composable fun ewsurfacevariantLight(context: Context): Color = DesignEngineController.ewsurfacevariantLight(context)
    @Composable fun ewsurfacevariantDark(context: Context): Color = DesignEngineController.ewsurfacevariantDark(context)

    // --- ON SURFACE VARIANT ---
    val eonsurfacevariant: Color @Composable get() = DesignEngineController.eonsurfacevariant(isSystemInDarkTheme())
    val eonsurfacevariantLight: Color @Composable get() = DesignEngineController.eonsurfacevariantLight()
    val eonsurfacevariantDark: Color @Composable get() = DesignEngineController.eonsurfacevariantDark()
    val efonsurfacevariant: Color @Composable get() = DesignEngineController.efonsurfacevariant(isSystemInDarkTheme())
    val efonsurfacevariantLight: Color @Composable get() = DesignEngineController.efonsurfacevariantLight()
    val efonsurfacevariantDark: Color @Composable get() = DesignEngineController.efonsurfacevariantDark()
    @Composable fun ewonsurfacevariant(context: Context): Color = DesignEngineController.ewonsurfacevariant(context, isSystemInDarkTheme())
    @Composable fun ewonsurfacevariantLight(context: Context): Color = DesignEngineController.ewonsurfacevariantLight(context)
    @Composable fun ewonsurfacevariantDark(context: Context): Color = DesignEngineController.ewonsurfacevariantDark(context)

    // --- INVERSE SURFACE ---
    val einversesurface: Color @Composable get() = DesignEngineController.einversesurface(isSystemInDarkTheme())
    val einversesurfaceLight: Color @Composable get() = DesignEngineController.einversesurfaceLight()
    val einversesurfaceDark: Color @Composable get() = DesignEngineController.einversesurfaceDark()
    val efinversesurface: Color @Composable get() = DesignEngineController.efinversesurface(isSystemInDarkTheme())
    val efinversesurfaceLight: Color @Composable get() = DesignEngineController.efinversesurfaceLight()
    val efinversesurfaceDark: Color @Composable get() = DesignEngineController.efinversesurfaceDark()
    @Composable fun ewinversesurface(context: Context): Color = DesignEngineController.ewinversesurface(context, isSystemInDarkTheme())
    @Composable fun ewinversesurfaceLight(context: Context): Color = DesignEngineController.ewinversesurfaceLight(context)
    @Composable fun ewinversesurfaceDark(context: Context): Color = DesignEngineController.ewinversesurfaceDark(context)

    // --- INVERSE ON SURFACE ---
    val einverseonsurface: Color @Composable get() = DesignEngineController.einverseonsurface(isSystemInDarkTheme())
    val einverseonsurfaceLight: Color @Composable get() = DesignEngineController.einverseonsurfaceLight()
    val einverseonsurfaceDark: Color @Composable get() = DesignEngineController.einverseonsurfaceDark()
    val efinverseonsurface: Color @Composable get() = DesignEngineController.efinverseonsurface(isSystemInDarkTheme())
    val efinverseonsurfaceLight: Color @Composable get() = DesignEngineController.efinverseonsurfaceLight()
    val efinverseonsurfaceDark: Color @Composable get() = DesignEngineController.efinverseonsurfaceDark()
    @Composable fun ewinverseonsurface(context: Context): Color = DesignEngineController.ewinverseonsurface(context, isSystemInDarkTheme())
    @Composable fun ewinverseonsurfaceLight(context: Context): Color = DesignEngineController.ewinverseonsurfaceLight(context)
    @Composable fun ewinverseonsurfaceDark(context: Context): Color = DesignEngineController.ewinverseonsurfaceDark(context)

    // --- SURFACE BRIGHT ---
    val esurfacebright: Color @Composable get() = DesignEngineController.esurfacebright(isSystemInDarkTheme())
    val esurfacebrightLight: Color @Composable get() = DesignEngineController.esurfacebrightLight()
    val esurfacebrightDark: Color @Composable get() = DesignEngineController.esurfacebrightDark()
    val efsurfacebright: Color @Composable get() = DesignEngineController.efsurfacebright(isSystemInDarkTheme())
    val efsurfacebrightLight: Color @Composable get() = DesignEngineController.efsurfacebrightLight()
    val efsurfacebrightDark: Color @Composable get() = DesignEngineController.efsurfacebrightDark()
    @Composable fun ewsurfacebright(context: Context): Color = DesignEngineController.ewsurfacebright(context, isSystemInDarkTheme())
    @Composable fun ewsurfacebrightLight(context: Context): Color = DesignEngineController.ewsurfacebrightLight(context)
    @Composable fun ewsurfacebrightDark(context: Context): Color = DesignEngineController.ewsurfacebrightDark(context)

    // --- SURFACE DIM ---
    val esurfacedim: Color @Composable get() = DesignEngineController.esurfacedim(isSystemInDarkTheme())
    val esurfacedimLight: Color @Composable get() = DesignEngineController.esurfacedimLight()
    val esurfacedimDark: Color @Composable get() = DesignEngineController.esurfacedimDark()
    val efsurfacedim: Color @Composable get() = DesignEngineController.efsurfacedim(isSystemInDarkTheme())
    val efsurfacedimLight: Color @Composable get() = DesignEngineController.efsurfacedimLight()
    val efsurfacedimDark: Color @Composable get() = DesignEngineController.efsurfacedimDark()
    @Composable fun ewsurfacedim(context: Context): Color = DesignEngineController.ewsurfacedim(context, isSystemInDarkTheme())
    @Composable fun ewsurfacedimLight(context: Context): Color = DesignEngineController.ewsurfacedimLight(context)
    @Composable fun ewsurfacedimDark(context: Context): Color = DesignEngineController.ewsurfacedimDark(context)

    // --- SURFACE CONTAINER LOW ---
    val esurfacecontainerlow: Color @Composable get() = DesignEngineController.esurfacecontainerlow(isSystemInDarkTheme())
    val esurfacecontainerlowLight: Color @Composable get() = DesignEngineController.esurfacecontainerlowLight()
    val esurfacecontainerlowDark: Color @Composable get() = DesignEngineController.esurfacecontainerlowDark()
    val efsurfacecontainerlow: Color @Composable get() = DesignEngineController.efsurfacecontainerlow(isSystemInDarkTheme())
    val efsurfacecontainerlowLight: Color @Composable get() = DesignEngineController.efsurfacecontainerlowLight()
    val efsurfacecontainerlowDark: Color @Composable get() = DesignEngineController.efsurfacecontainerlowDark()
    @Composable fun ewsurfacecontainerlow(context: Context): Color = DesignEngineController.ewsurfacecontainerlow(context, isSystemInDarkTheme())
    @Composable fun ewsurfacecontainerlowLight(context: Context): Color = DesignEngineController.ewsurfacecontainerlowLight(context)
    @Composable fun ewsurfacecontainerlowDark(context: Context): Color = DesignEngineController.ewsurfacecontainerlowDark(context)

    // --- SURFACE CONTAINER HIGH ---
    val esurfacecontainerhigh: Color @Composable get() = DesignEngineController.esurfacecontainerhigh(isSystemInDarkTheme())
    val esurfacecontainerhighLight: Color @Composable get() = DesignEngineController.esurfacecontainerhighLight()
    val esurfacecontainerhighDark: Color @Composable get() = DesignEngineController.esurfacecontainerhighDark()
    val efsurfacecontainerhigh: Color @Composable get() = DesignEngineController.efsurfacecontainerhigh(isSystemInDarkTheme())
    val efsurfacecontainerhighLight: Color @Composable get() = DesignEngineController.efsurfacecontainerhighLight()
    val efsurfacecontainerhighDark: Color @Composable get() = DesignEngineController.efsurfacecontainerhighDark()
    @Composable fun ewsurfacecontainerhigh(context: Context): Color = DesignEngineController.ewsurfacecontainerhigh(context, isSystemInDarkTheme())
    @Composable fun ewsurfacecontainerhighLight(context: Context): Color = DesignEngineController.ewsurfacecontainerhighLight(context)
    @Composable fun ewsurfacecontainerhighDark(context: Context): Color = DesignEngineController.ewsurfacecontainerhighDark(context)

    // --- SURFACE CONTAINER LOWEST ---
    val esurfacecontainerlowest: Color @Composable get() = DesignEngineController.esurfacecontainerlowest(isSystemInDarkTheme())
    val esurfacecontainerlowestLight: Color @Composable get() = DesignEngineController.esurfacecontainerlowestLight()
    val esurfacecontainerlowestDark: Color @Composable get() = DesignEngineController.esurfacecontainerlowestDark()
    val efsurfacecontainerlowest: Color @Composable get() = DesignEngineController.efsurfacecontainerlowest(isSystemInDarkTheme())
    val efsurfacecontainerlowestLight: Color @Composable get() = DesignEngineController.efsurfacecontainerlowestLight()
    val efsurfacecontainerlowestDark: Color @Composable get() = DesignEngineController.efsurfacecontainerlowestDark()
    @Composable fun ewsurfacecontainerlowest(context: Context): Color = DesignEngineController.ewsurfacecontainerlowest(context, isSystemInDarkTheme())
    @Composable fun ewsurfacecontainerlowestLight(context: Context): Color = DesignEngineController.ewsurfacecontainerlowestLight(context)
    @Composable fun ewsurfacecontainerlowestDark(context: Context): Color = DesignEngineController.ewsurfacecontainerlowestDark(context)

    // --- SURFACE CONTAINER HIGHEST ---
    val esurfacecontainerhighest: Color @Composable get() = DesignEngineController.esurfacecontainerhighest(isSystemInDarkTheme())
    val esurfacecontainerhighestLight: Color @Composable get() = DesignEngineController.esurfacecontainerhighestLight()
    val esurfacecontainerhighestDark: Color @Composable get() = DesignEngineController.esurfacecontainerhighestDark()
    val efsurfacecontainerhighest: Color @Composable get() = DesignEngineController.efsurfacecontainerhighest(isSystemInDarkTheme())
    val efsurfacecontainerhighestLight: Color @Composable get() = DesignEngineController.efsurfacecontainerhighestLight()
    val efsurfacecontainerhighestDark: Color @Composable get() = DesignEngineController.efsurfacecontainerhighestDark()
    @Composable fun ewsurfacecontainerhighest(context: Context): Color = DesignEngineController.ewsurfacecontainerhighest(context, isSystemInDarkTheme())
    @Composable fun ewsurfacecontainerhighestLight(context: Context): Color = DesignEngineController.ewsurfacecontainerhighestLight(context)
    @Composable fun ewsurfacecontainerhighestDark(context: Context): Color = DesignEngineController.ewsurfacecontainerhighestDark(context)

    // --- SURFACE CONTAINER ---
    val esurfacecontainer: Color @Composable get() = DesignEngineController.esurfacecontainer(isSystemInDarkTheme())
    val esurfacecontainerLight: Color @Composable get() = DesignEngineController.esurfacecontainerLight()
    val esurfacecontainerDark: Color @Composable get() = DesignEngineController.esurfacecontainerDark()
    val efsurfacecontainer: Color @Composable get() = DesignEngineController.efsurfacecontainer(isSystemInDarkTheme())
    val efsurfacecontainerLight: Color @Composable get() = DesignEngineController.efsurfacecontainerLight()
    val efsurfacecontainerDark: Color @Composable get() = DesignEngineController.efsurfacecontainerDark()
    @Composable fun ewsurfacecontainer(context: Context): Color = DesignEngineController.ewsurfacecontainer(context, isSystemInDarkTheme())
    @Composable fun ewsurfacecontainerLight(context: Context): Color = DesignEngineController.ewsurfacecontainerLight(context)
    @Composable fun ewsurfacecontainerDark(context: Context): Color = DesignEngineController.ewsurfacecontainerDark(context)

    // --- PRIMARY ---
    val eprimary: Color @Composable get() = DesignEngineController.eprimary(isSystemInDarkTheme())
    val eprimaryLight: Color @Composable get() = DesignEngineController.eprimaryLight()
    val eprimaryDark: Color @Composable get() = DesignEngineController.eprimaryDark()
    val efprimary: Color @Composable get() = DesignEngineController.efprimary(isSystemInDarkTheme())
    val efprimaryLight: Color @Composable get() = DesignEngineController.efprimaryLight()
    val efprimaryDark: Color @Composable get() = DesignEngineController.efprimaryDark()
    @Composable fun ewprimary(context: Context): Color = DesignEngineController.ewprimary(context, isSystemInDarkTheme())
    @Composable fun ewprimaryLight(context: Context): Color = DesignEngineController.ewprimaryLight(context)
    @Composable fun ewprimaryDark(context: Context): Color = DesignEngineController.ewprimaryDark(context)

    // --- ON PRIMARY ---
    val eonprimary: Color @Composable get() = DesignEngineController.eonprimary(isSystemInDarkTheme())
    val eonprimaryLight: Color @Composable get() = DesignEngineController.eonprimaryLight()
    val eonprimaryDark: Color @Composable get() = DesignEngineController.eonprimaryDark()
    val efonprimary: Color @Composable get() = DesignEngineController.efonprimary(isSystemInDarkTheme())
    val efonprimaryLight: Color @Composable get() = DesignEngineController.efonprimaryLight()
    val efonprimaryDark: Color @Composable get() = DesignEngineController.efonprimaryDark()
    @Composable fun ewonprimary(context: Context): Color = DesignEngineController.ewonprimary(context, isSystemInDarkTheme())
    @Composable fun ewonprimaryLight(context: Context): Color = DesignEngineController.ewonprimaryLight(context)
    @Composable fun ewonprimaryDark(context: Context): Color = DesignEngineController.ewonprimaryDark(context)

    // --- PRIMARY CONTAINER ---
    val eprimarycontainer: Color @Composable get() = DesignEngineController.eprimarycontainer(isSystemInDarkTheme())
    val eprimarycontainerLight: Color @Composable get() = DesignEngineController.eprimarycontainerLight()
    val eprimarycontainerDark: Color @Composable get() = DesignEngineController.eprimarycontainerDark()
    val efprimarycontainer: Color @Composable get() = DesignEngineController.efprimarycontainer(isSystemInDarkTheme())
    val efprimarycontainerLight: Color @Composable get() = DesignEngineController.efprimarycontainerLight()
    val efprimarycontainerDark: Color @Composable get() = DesignEngineController.efprimarycontainerDark()
    @Composable fun ewprimarycontainer(context: Context): Color = DesignEngineController.ewprimarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewprimarycontainerLight(context: Context): Color = DesignEngineController.ewprimarycontainerLight(context)
    @Composable fun ewprimarycontainerDark(context: Context): Color = DesignEngineController.ewprimarycontainerDark(context)

    // --- ON PRIMARY CONTAINER ---
    val eonprimarycontainer: Color @Composable get() = DesignEngineController.eonprimarycontainer(isSystemInDarkTheme())
    val eonprimarycontainerLight: Color @Composable get() = DesignEngineController.eonprimarycontainerLight()
    val eonprimarycontainerDark: Color @Composable get() = DesignEngineController.eonprimarycontainerDark()
    val efonprimarycontainer: Color @Composable get() = DesignEngineController.efonprimarycontainer(isSystemInDarkTheme())
    val efonprimarycontainerLight: Color @Composable get() = DesignEngineController.efonprimarycontainerLight()
    val efonprimarycontainerDark: Color @Composable get() = DesignEngineController.efonprimarycontainerDark()
    @Composable fun ewonprimarycontainer(context: Context): Color = DesignEngineController.ewonprimarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewonprimarycontainerLight(context: Context): Color = DesignEngineController.ewonprimarycontainerLight(context)
    @Composable fun ewonprimarycontainerDark(context: Context): Color = DesignEngineController.ewonprimarycontainerDark(context)

    // --- PRIMARY FIXED ---
    val eprimaryfixed: Color @Composable get() = DesignEngineController.eprimaryfixed(isSystemInDarkTheme())
    val eprimaryfixedLight: Color @Composable get() = DesignEngineController.eprimaryfixedLight()
    val eprimaryfixedDark: Color @Composable get() = DesignEngineController.eprimaryfixedDark()
    val efprimaryfixed: Color @Composable get() = DesignEngineController.efprimaryfixed(isSystemInDarkTheme())
    val efprimaryfixedLight: Color @Composable get() = DesignEngineController.efprimaryfixedLight()
    val efprimaryfixedDark: Color @Composable get() = DesignEngineController.efprimaryfixedDark()
    @Composable fun ewprimaryfixed(context: Context): Color = DesignEngineController.ewprimaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewprimaryfixedLight(context: Context): Color = DesignEngineController.ewprimaryfixedLight(context)
    @Composable fun ewprimaryfixedDark(context: Context): Color = DesignEngineController.ewprimaryfixedDark(context)

    // --- PRIMARY FIXED DIM ---
    val eprimaryfixeddim: Color @Composable get() = DesignEngineController.eprimaryfixeddim(isSystemInDarkTheme())
    val eprimaryfixeddimLight: Color @Composable get() = DesignEngineController.eprimaryfixeddimLight()
    val eprimaryfixeddimDark: Color @Composable get() = DesignEngineController.eprimaryfixeddimDark()
    val efprimaryfixeddim: Color @Composable get() = DesignEngineController.efprimaryfixeddim(isSystemInDarkTheme())
    val efprimaryfixeddimLight: Color @Composable get() = DesignEngineController.efprimaryfixeddimLight()
    val efprimaryfixeddimDark: Color @Composable get() = DesignEngineController.efprimaryfixeddimDark()
    @Composable fun ewprimaryfixeddim(context: Context): Color = DesignEngineController.ewprimaryfixeddim(context, isSystemInDarkTheme())
    @Composable fun ewprimaryfixeddimLight(context: Context): Color = DesignEngineController.ewprimaryfixeddimLight(context)
    @Composable fun ewprimaryfixeddimDark(context: Context): Color = DesignEngineController.ewprimaryfixeddimDark(context)

    // --- ON PRIMARY FIXED ---
    val eonprimaryfixed: Color @Composable get() = DesignEngineController.eonprimaryfixed(isSystemInDarkTheme())
    val eonprimaryfixedLight: Color @Composable get() = DesignEngineController.eonprimaryfixedLight()
    val eonprimaryfixedDark: Color @Composable get() = DesignEngineController.eonprimaryfixedDark()
    val efonprimaryfixed: Color @Composable get() = DesignEngineController.efonprimaryfixed(isSystemInDarkTheme())
    val efonprimaryfixedLight: Color @Composable get() = DesignEngineController.efonprimaryfixedLight()
    val efonprimaryfixedDark: Color @Composable get() = DesignEngineController.efonprimaryfixedDark()
    @Composable fun ewonprimaryfixed(context: Context): Color = DesignEngineController.ewonprimaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewonprimaryfixedLight(context: Context): Color = DesignEngineController.ewonprimaryfixedLight(context)
    @Composable fun ewonprimaryfixedDark(context: Context): Color = DesignEngineController.ewonprimaryfixedDark(context)

    // --- ON PRIMARY FIXED VARIANT ---
    val eonprimaryfixedvariant: Color @Composable get() = DesignEngineController.eonprimaryfixedvariant(isSystemInDarkTheme())
    val eonprimaryfixedvariantLight: Color @Composable get() = DesignEngineController.eonprimaryfixedvariantLight()
    val eonprimaryfixedvariantDark: Color @Composable get() = DesignEngineController.eonprimaryfixedvariantDark()
    val efonprimaryfixedvariant: Color @Composable get() = DesignEngineController.efonprimaryfixedvariant(isSystemInDarkTheme())
    val efonprimaryfixedvariantLight: Color @Composable get() = DesignEngineController.efonprimaryfixedvariantLight()
    val efonprimaryfixedvariantDark: Color @Composable get() = DesignEngineController.efonprimaryfixedvariantDark()
    @Composable fun ewonprimaryfixedvariant(context: Context): Color = DesignEngineController.ewonprimaryfixedvariant(context, isSystemInDarkTheme())
    @Composable fun ewonprimaryfixedvariantLight(context: Context): Color = DesignEngineController.ewonprimaryfixedvariantLight(context)
    @Composable fun ewonprimaryfixedvariantDark(context: Context): Color = DesignEngineController.ewonprimaryfixedvariantDark(context)

    // --- INVERSE PRIMARY ---
    val einverseprimary: Color @Composable get() = DesignEngineController.einverseprimary(isSystemInDarkTheme())
    val einverseprimaryLight: Color @Composable get() = DesignEngineController.einverseprimaryLight()
    val einverseprimaryDark: Color @Composable get() = DesignEngineController.einverseprimaryDark()
    val efinverseprimary: Color @Composable get() = DesignEngineController.efinverseprimary(isSystemInDarkTheme())
    val efinverseprimaryLight: Color @Composable get() = DesignEngineController.efinverseprimaryLight()
    val efinverseprimaryDark: Color @Composable get() = DesignEngineController.efinverseprimaryDark()
    @Composable fun ewinverseprimary(context: Context): Color = DesignEngineController.ewinverseprimary(context, isSystemInDarkTheme())
    @Composable fun ewinverseprimaryLight(context: Context): Color = DesignEngineController.ewinverseprimaryLight(context)
    @Composable fun ewinverseprimaryDark(context: Context): Color = DesignEngineController.ewinverseprimaryDark(context)

    // --- SECONDARY ---
    val esecondary: Color @Composable get() = DesignEngineController.esecondary(isSystemInDarkTheme())
    val esecondaryLight: Color @Composable get() = DesignEngineController.esecondaryLight()
    val esecondaryDark: Color @Composable get() = DesignEngineController.esecondaryDark()
    val efsecondary: Color @Composable get() = DesignEngineController.efsecondary(isSystemInDarkTheme())
    val efsecondaryLight: Color @Composable get() = DesignEngineController.efsecondaryLight()
    val efsecondaryDark: Color @Composable get() = DesignEngineController.efsecondaryDark()
    @Composable fun ewsecondary(context: Context): Color = DesignEngineController.ewsecondary(context, isSystemInDarkTheme())
    @Composable fun ewsecondaryLight(context: Context): Color = DesignEngineController.ewsecondaryLight(context)
    @Composable fun ewsecondaryDark(context: Context): Color = DesignEngineController.ewsecondaryDark(context)

    // --- ON SECONDARY ---
    val eonsecondary: Color @Composable get() = DesignEngineController.eonsecondary(isSystemInDarkTheme())
    val eonsecondaryLight: Color @Composable get() = DesignEngineController.eonsecondaryLight()
    val eonsecondaryDark: Color @Composable get() = DesignEngineController.eonsecondaryDark()
    val efonsecondary: Color @Composable get() = DesignEngineController.efonsecondary(isSystemInDarkTheme())
    val efonsecondaryLight: Color @Composable get() = DesignEngineController.efonsecondaryLight()
    val efonsecondaryDark: Color @Composable get() = DesignEngineController.efonsecondaryDark()
    @Composable fun ewonsecondary(context: Context): Color = DesignEngineController.ewonsecondary(context, isSystemInDarkTheme())
    @Composable fun ewonsecondaryLight(context: Context): Color = DesignEngineController.ewonsecondaryLight(context)
    @Composable fun ewonsecondaryDark(context: Context): Color = DesignEngineController.ewonsecondaryDark(context)

    // --- SECONDARY CONTAINER ---
    val esecondarycontainer: Color @Composable get() = DesignEngineController.esecondarycontainer(isSystemInDarkTheme())
    val esecondarycontainerLight: Color @Composable get() = DesignEngineController.esecondarycontainerLight()
    val esecondarycontainerDark: Color @Composable get() = DesignEngineController.esecondarycontainerDark()
    val efsecondarycontainer: Color @Composable get() = DesignEngineController.efsecondarycontainer(isSystemInDarkTheme())
    val efsecondarycontainerLight: Color @Composable get() = DesignEngineController.efsecondarycontainerLight()
    val efsecondarycontainerDark: Color @Composable get() = DesignEngineController.efsecondarycontainerDark()
    @Composable fun ewsecondarycontainer(context: Context): Color = DesignEngineController.ewsecondarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewsecondarycontainerLight(context: Context): Color = DesignEngineController.ewsecondarycontainerLight(context)
    @Composable fun ewsecondarycontainerDark(context: Context): Color = DesignEngineController.ewsecondarycontainerDark(context)

    // --- ON SECONDARY CONTAINER ---
    val eonsecondarycontainer: Color @Composable get() = DesignEngineController.eonsecondarycontainer(isSystemInDarkTheme())
    val eonsecondarycontainerLight: Color @Composable get() = DesignEngineController.eonsecondarycontainerLight()
    val eonsecondarycontainerDark: Color @Composable get() = DesignEngineController.eonsecondarycontainerDark()
    val efonsecondarycontainer: Color @Composable get() = DesignEngineController.efonsecondarycontainer(isSystemInDarkTheme())
    val efonsecondarycontainerLight: Color @Composable get() = DesignEngineController.efonsecondarycontainerLight()
    val efonsecondarycontainerDark: Color @Composable get() = DesignEngineController.efonsecondarycontainerDark()
    @Composable fun ewonsecondarycontainer(context: Context): Color = DesignEngineController.ewonsecondarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewonsecondarycontainerLight(context: Context): Color = DesignEngineController.ewonsecondarycontainerLight(context)
    @Composable fun ewonsecondarycontainerDark(context: Context): Color = DesignEngineController.ewonsecondarycontainerDark(context)

    // --- SECONDARY FIXED ---
    val esecondaryfixed: Color @Composable get() = DesignEngineController.esecondaryfixed(isSystemInDarkTheme())
    val esecondaryfixedLight: Color @Composable get() = DesignEngineController.esecondaryfixedLight()
    val esecondaryfixedDark: Color @Composable get() = DesignEngineController.esecondaryfixedDark()
    val efsecondaryfixed: Color @Composable get() = DesignEngineController.efsecondaryfixed(isSystemInDarkTheme())
    val efsecondaryfixedLight: Color @Composable get() = DesignEngineController.efsecondaryfixedLight()
    val efsecondaryfixedDark: Color @Composable get() = DesignEngineController.efsecondaryfixedDark()
    @Composable fun ewsecondaryfixed(context: Context): Color = DesignEngineController.ewsecondaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewsecondaryfixedLight(context: Context): Color = DesignEngineController.ewsecondaryfixedLight(context)
    @Composable fun ewsecondaryfixedDark(context: Context): Color = DesignEngineController.ewsecondaryfixedDark(context)

    // --- SECONDARY FIXED DIM ---
    val esecondaryfixeddim: Color @Composable get() = DesignEngineController.esecondaryfixeddim(isSystemInDarkTheme())
    val esecondaryfixeddimLight: Color @Composable get() = DesignEngineController.esecondaryfixeddimLight()
    val esecondaryfixeddimDark: Color @Composable get() = DesignEngineController.esecondaryfixeddimDark()
    val efsecondaryfixeddim: Color @Composable get() = DesignEngineController.efsecondaryfixeddim(isSystemInDarkTheme())
    val efsecondaryfixeddimLight: Color @Composable get() = DesignEngineController.efsecondaryfixeddimLight()
    val efsecondaryfixeddimDark: Color @Composable get() = DesignEngineController.efsecondaryfixeddimDark()
    @Composable fun ewsecondaryfixeddim(context: Context): Color = DesignEngineController.ewsecondaryfixeddim(context, isSystemInDarkTheme())
    @Composable fun ewsecondaryfixeddimLight(context: Context): Color = DesignEngineController.ewsecondaryfixeddimLight(context)
    @Composable fun ewsecondaryfixeddimDark(context: Context): Color = DesignEngineController.ewsecondaryfixeddimDark(context)

    // --- ON SECONDARY FIXED ---
    val eonsecondaryfixed: Color @Composable get() = DesignEngineController.eonsecondaryfixed(isSystemInDarkTheme())
    val eonsecondaryfixedLight: Color @Composable get() = DesignEngineController.eonsecondaryfixedLight()
    val eonsecondaryfixedDark: Color @Composable get() = DesignEngineController.eonsecondaryfixedDark()
    val efonsecondaryfixed: Color @Composable get() = DesignEngineController.efonsecondaryfixed(isSystemInDarkTheme())
    val efonsecondaryfixedLight: Color @Composable get() = DesignEngineController.efonsecondaryfixedLight()
    val efonsecondaryfixedDark: Color @Composable get() = DesignEngineController.efonsecondaryfixedDark()
    @Composable fun ewonsecondaryfixed(context: Context): Color = DesignEngineController.ewonsecondaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewonsecondaryfixedLight(context: Context): Color = DesignEngineController.ewonsecondaryfixedLight(context)
    @Composable fun ewonsecondaryfixedDark(context: Context): Color = DesignEngineController.ewonsecondaryfixedDark(context)

    // --- ON SECONDARY FIXED VARIANT ---
    val eonsecondaryfixedvariant: Color @Composable get() = DesignEngineController.eonsecondaryfixedvariant(isSystemInDarkTheme())
    val eonsecondaryfixedvariantLight: Color @Composable get() = DesignEngineController.eonsecondaryfixedvariantLight()
    val eonsecondaryfixedvariantDark: Color @Composable get() = DesignEngineController.eonsecondaryfixedvariantDark()
    val efonsecondaryfixedvariant: Color @Composable get() = DesignEngineController.efonsecondaryfixedvariant(isSystemInDarkTheme())
    val efonsecondaryfixedvariantLight: Color @Composable get() = DesignEngineController.efonsecondaryfixedvariantLight()
    val efonsecondaryfixedvariantDark: Color @Composable get() = DesignEngineController.efonsecondaryfixedvariantDark()
    @Composable fun ewonsecondaryfixedvariant(context: Context): Color = DesignEngineController.ewonsecondaryfixedvariant(context, isSystemInDarkTheme())
    @Composable fun ewonsecondaryfixedvariantLight(context: Context): Color = DesignEngineController.ewonsecondaryfixedvariantLight(context)
    @Composable fun ewonsecondaryfixedvariantDark(context: Context): Color = DesignEngineController.ewonsecondaryfixedvariantDark(context)

    // --- TERTIARY ---
    val etertiary: Color @Composable get() = DesignEngineController.etertiary(isSystemInDarkTheme())
    val etertiaryLight: Color @Composable get() = DesignEngineController.etertiaryLight()
    val etertiaryDark: Color @Composable get() = DesignEngineController.etertiaryDark()
    val eftertiary: Color @Composable get() = DesignEngineController.eftertiary(isSystemInDarkTheme())
    val eftertiaryLight: Color @Composable get() = DesignEngineController.eftertiaryLight()
    val eftertiaryDark: Color @Composable get() = DesignEngineController.eftertiaryDark()
    @Composable fun ewtertiary(context: Context): Color = DesignEngineController.ewtertiary(context, isSystemInDarkTheme())
    @Composable fun ewtertiaryLight(context: Context): Color = DesignEngineController.ewtertiaryLight(context)
    @Composable fun ewtertiaryDark(context: Context): Color = DesignEngineController.ewtertiaryDark(context)

    // --- ON TERTIARY ---
    val eontertiary: Color @Composable get() = DesignEngineController.eontertiary(isSystemInDarkTheme())
    val eontertiaryLight: Color @Composable get() = DesignEngineController.eontertiaryLight()
    val eontertiaryDark: Color @Composable get() = DesignEngineController.eontertiaryDark()
    val efontertiary: Color @Composable get() = DesignEngineController.efontertiary(isSystemInDarkTheme())
    val efontertiaryLight: Color @Composable get() = DesignEngineController.efontertiaryLight()
    val efontertiaryDark: Color @Composable get() = DesignEngineController.efontertiaryDark()
    @Composable fun ewontertiary(context: Context): Color = DesignEngineController.ewontertiary(context, isSystemInDarkTheme())
    @Composable fun ewontertiaryLight(context: Context): Color = DesignEngineController.ewontertiaryLight(context)
    @Composable fun ewontertiaryDark(context: Context): Color = DesignEngineController.ewontertiaryDark(context)

    // --- TERTIARY CONTAINER ---
    val etertiarycontainer: Color @Composable get() = DesignEngineController.etertiarycontainer(isSystemInDarkTheme())
    val etertiarycontainerLight: Color @Composable get() = DesignEngineController.etertiarycontainerLight()
    val etertiarycontainerDark: Color @Composable get() = DesignEngineController.etertiarycontainerDark()
    val eftertiarycontainer: Color @Composable get() = DesignEngineController.eftertiarycontainer(isSystemInDarkTheme())
    val eftertiarycontainerLight: Color @Composable get() = DesignEngineController.eftertiarycontainerLight()
    val eftertiarycontainerDark: Color @Composable get() = DesignEngineController.eftertiarycontainerDark()
    @Composable fun ewtertiarycontainer(context: Context): Color = DesignEngineController.ewtertiarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewtertiarycontainerLight(context: Context): Color = DesignEngineController.ewtertiarycontainerLight(context)
    @Composable fun ewtertiarycontainerDark(context: Context): Color = DesignEngineController.ewtertiarycontainerDark(context)

    // --- ON TERTIARY CONTAINER ---
    val eontertiarycontainer: Color @Composable get() = DesignEngineController.eontertiarycontainer(isSystemInDarkTheme())
    val eontertiarycontainerLight: Color @Composable get() = DesignEngineController.eontertiarycontainerLight()
    val eontertiarycontainerDark: Color @Composable get() = DesignEngineController.eontertiarycontainerDark()
    val efontertiarycontainer: Color @Composable get() = DesignEngineController.efontertiarycontainer(isSystemInDarkTheme())
    val efontertiarycontainerLight: Color @Composable get() = DesignEngineController.efontertiarycontainerLight()
    val efontertiarycontainerDark: Color @Composable get() = DesignEngineController.efontertiarycontainerDark()
    @Composable fun ewontertiarycontainer(context: Context): Color = DesignEngineController.ewontertiarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewontertiarycontainerLight(context: Context): Color = DesignEngineController.ewontertiarycontainerLight(context)
    @Composable fun ewontertiarycontainerDark(context: Context): Color = DesignEngineController.ewontertiarycontainerDark(context)

    // --- TERTIARY FIXED ---
    val etertiaryfixed: Color @Composable get() = DesignEngineController.etertiaryfixed(isSystemInDarkTheme())
    val etertiaryfixedLight: Color @Composable get() = DesignEngineController.etertiaryfixedLight()
    val etertiaryfixedDark: Color @Composable get() = DesignEngineController.etertiaryfixedDark()
    val eftertiaryfixed: Color @Composable get() = DesignEngineController.eftertiaryfixed(isSystemInDarkTheme())
    val eftertiaryfixedLight: Color @Composable get() = DesignEngineController.eftertiaryfixedLight()
    val eftertiaryfixedDark: Color @Composable get() = DesignEngineController.eftertiaryfixedDark()
    @Composable fun ewtertiaryfixed(context: Context): Color = DesignEngineController.ewtertiaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewtertiaryfixedLight(context: Context): Color = DesignEngineController.ewtertiaryfixedLight(context)
    @Composable fun ewtertiaryfixedDark(context: Context): Color = DesignEngineController.ewtertiaryfixedDark(context)

    // --- TERTIARY FIXED DIM ---
    val etertiaryfixeddim: Color @Composable get() = DesignEngineController.etertiaryfixeddim(isSystemInDarkTheme())
    val etertiaryfixeddimLight: Color @Composable get() = DesignEngineController.etertiaryfixeddimLight()
    val etertiaryfixeddimDark: Color @Composable get() = DesignEngineController.etertiaryfixeddimDark()
    val eftertiaryfixeddim: Color @Composable get() = DesignEngineController.eftertiaryfixeddim(isSystemInDarkTheme())
    val eftertiaryfixeddimLight: Color @Composable get() = DesignEngineController.eftertiaryfixeddimLight()
    val eftertiaryfixeddimDark: Color @Composable get() = DesignEngineController.eftertiaryfixeddimDark()
    @Composable fun ewtertiaryfixeddim(context: Context): Color = DesignEngineController.ewtertiaryfixeddim(context, isSystemInDarkTheme())
    @Composable fun ewtertiaryfixeddimLight(context: Context): Color = DesignEngineController.ewtertiaryfixeddimLight(context)
    @Composable fun ewtertiaryfixeddimDark(context: Context): Color = DesignEngineController.ewtertiaryfixeddimDark(context)

    // --- ON TERTIARY FIXED ---
    val eontertiaryfixed: Color @Composable get() = DesignEngineController.eontertiaryfixed(isSystemInDarkTheme())
    val eontertiaryfixedLight: Color @Composable get() = DesignEngineController.eontertiaryfixedLight()
    val eontertiaryfixedDark: Color @Composable get() = DesignEngineController.eontertiaryfixedDark()
    val efontertiaryfixed: Color @Composable get() = DesignEngineController.efontertiaryfixed(isSystemInDarkTheme())
    val efontertiaryfixedLight: Color @Composable get() = DesignEngineController.efontertiaryfixedLight()
    val efontertiaryfixedDark: Color @Composable get() = DesignEngineController.efontertiaryfixedDark()
    @Composable fun ewontertiaryfixed(context: Context): Color = DesignEngineController.ewontertiaryfixed(context, isSystemInDarkTheme())
    @Composable fun ewontertiaryfixedLight(context: Context): Color = DesignEngineController.ewontertiaryfixedLight(context)
    @Composable fun ewontertiaryfixedDark(context: Context): Color = DesignEngineController.ewontertiaryfixedDark(context)

    // --- ON TERTIARY FIXED VARIANT ---
    val eontertiaryfixedvariant: Color @Composable get() = DesignEngineController.eontertiaryfixedvariant(isSystemInDarkTheme())
    val eontertiaryfixedvariantLight: Color @Composable get() = DesignEngineController.eontertiaryfixedvariantLight()
    val eontertiaryfixedvariantDark: Color @Composable get() = DesignEngineController.eontertiaryfixedvariantDark()
    val efontertiaryfixedvariant: Color @Composable get() = DesignEngineController.efontertiaryfixedvariant(isSystemInDarkTheme())
    val efontertiaryfixedvariantLight: Color @Composable get() = DesignEngineController.efontertiaryfixedvariantLight()
    val efontertiaryfixedvariantDark: Color @Composable get() = DesignEngineController.efontertiaryfixedvariantDark()
    @Composable fun ewontertiaryfixedvariant(context: Context): Color = DesignEngineController.ewontertiaryfixedvariant(context, isSystemInDarkTheme())
    @Composable fun ewontertiaryfixedvariantLight(context: Context): Color = DesignEngineController.ewontertiaryfixedvariantLight(context)
    @Composable fun ewontertiaryfixedvariantDark(context: Context): Color = DesignEngineController.ewontertiaryfixedvariantDark(context)

    // --- ERROR ---
    val eerror: Color @Composable get() = DesignEngineController.eerror(isSystemInDarkTheme())
    val eerrorLight: Color @Composable get() = DesignEngineController.eerrorLight()
    val eerrorDark: Color @Composable get() = DesignEngineController.eerrorDark()
    val eferror: Color @Composable get() = DesignEngineController.eferror(isSystemInDarkTheme())
    val eferrorLight: Color @Composable get() = DesignEngineController.eferrorLight()
    val eferrorDark: Color @Composable get() = DesignEngineController.eferrorDark()
    @Composable fun ewerror(context: Context): Color = DesignEngineController.ewerror(context, isSystemInDarkTheme())
    @Composable fun ewerrorLight(context: Context): Color = DesignEngineController.ewerrorLight(context)
    @Composable fun ewerrorDark(context: Context): Color = DesignEngineController.ewerrorDark(context)

    // --- ON ERROR ---
    val eonerror: Color @Composable get() = DesignEngineController.eonerror(isSystemInDarkTheme())
    val eonerrorLight: Color @Composable get() = DesignEngineController.eonerrorLight()
    val eonerrorDark: Color @Composable get() = DesignEngineController.eonerrorDark()
    val efonerror: Color @Composable get() = DesignEngineController.efonerror(isSystemInDarkTheme())
    val efonerrorLight: Color @Composable get() = DesignEngineController.efonerrorLight()
    val efonerrorDark: Color @Composable get() = DesignEngineController.efonerrorDark()
    @Composable fun ewonerror(context: Context): Color = DesignEngineController.ewonerror(context, isSystemInDarkTheme())
    @Composable fun ewonerrorLight(context: Context): Color = DesignEngineController.ewonerrorLight(context)
    @Composable fun ewonerrorDark(context: Context): Color = DesignEngineController.ewonerrorDark(context)

    // --- ERROR CONTAINER ---
    val eerrorcontainer: Color @Composable get() = DesignEngineController.eerrorcontainer(isSystemInDarkTheme())
    val eerrorcontainerLight: Color @Composable get() = DesignEngineController.eerrorcontainerLight()
    val eerrorcontainerDark: Color @Composable get() = DesignEngineController.eerrorcontainerDark()
    val eferrorcontainer: Color @Composable get() = DesignEngineController.eferrorcontainer(isSystemInDarkTheme())
    val eferrorcontainerLight: Color @Composable get() = DesignEngineController.eferrorcontainerLight()
    val eferrorcontainerDark: Color @Composable get() = DesignEngineController.eferrorcontainerDark()
    @Composable fun ewerrorcontainer(context: Context): Color = DesignEngineController.ewerrorcontainer(context, isSystemInDarkTheme())
    @Composable fun ewerrorcontainerLight(context: Context): Color = DesignEngineController.ewerrorcontainerLight(context)
    @Composable fun ewerrorcontainerDark(context: Context): Color = DesignEngineController.ewerrorcontainerDark(context)

    // --- ON ERROR CONTAINER ---
    val eonerrorcontainer: Color @Composable get() = DesignEngineController.eonerrorcontainer(isSystemInDarkTheme())
    val eonerrorcontainerLight: Color @Composable get() = DesignEngineController.eonerrorcontainerLight()
    val eonerrorcontainerDark: Color @Composable get() = DesignEngineController.eonerrorcontainerDark()
    val efonerrorcontainer: Color @Composable get() = DesignEngineController.efonerrorcontainer(isSystemInDarkTheme())
    val efonerrorcontainerLight: Color @Composable get() = DesignEngineController.efonerrorcontainerLight()
    val efonerrorcontainerDark: Color @Composable get() = DesignEngineController.efonerrorcontainerDark()
    @Composable fun ewonerrorcontainer(context: Context): Color = DesignEngineController.ewonerrorcontainer(context, isSystemInDarkTheme())
    @Composable fun ewonerrorcontainerLight(context: Context): Color = DesignEngineController.ewonerrorcontainerLight(context)
    @Composable fun ewonerrorcontainerDark(context: Context): Color = DesignEngineController.ewonerrorcontainerDark(context)

    // --- OUTLINE ---
    val eoutline: Color @Composable get() = DesignEngineController.eoutline(isSystemInDarkTheme())
    val eoutlineLight: Color @Composable get() = DesignEngineController.eoutlineLight()
    val eoutlineDark: Color @Composable get() = DesignEngineController.eoutlineDark()
    val efoutline: Color @Composable get() = DesignEngineController.efoutline(isSystemInDarkTheme())
    val efoutlineLight: Color @Composable get() = DesignEngineController.efoutlineLight()
    val efoutlineDark: Color @Composable get() = DesignEngineController.efoutlineDark()
    @Composable fun ewoutline(context: Context): Color = DesignEngineController.ewoutline(context, isSystemInDarkTheme())
    @Composable fun ewoutlineLight(context: Context): Color = DesignEngineController.ewoutlineLight(context)
    @Composable fun ewoutlineDark(context: Context): Color = DesignEngineController.ewoutlineDark(context)

    // --- OUTLINE VARIANT ---
    val eoutlinevariant: Color @Composable get() = DesignEngineController.eoutlinevariant(isSystemInDarkTheme())
    val eoutlinevariantLight: Color @Composable get() = DesignEngineController.eoutlinevariantLight()
    val eoutlinevariantDark: Color @Composable get() = DesignEngineController.eoutlinevariantDark()
    val efoutlinevariant: Color @Composable get() = DesignEngineController.efoutlinevariant(isSystemInDarkTheme())
    val efoutlinevariantLight: Color @Composable get() = DesignEngineController.efoutlinevariantLight()
    val efoutlinevariantDark: Color @Composable get() = DesignEngineController.efoutlinevariantDark()
    @Composable fun ewoutlinevariant(context: Context): Color = DesignEngineController.ewoutlinevariant(context, isSystemInDarkTheme())
    @Composable fun ewoutlinevariantLight(context: Context): Color = DesignEngineController.ewoutlinevariantLight(context)
    @Composable fun ewoutlinevariantDark(context: Context): Color = DesignEngineController.ewoutlinevariantDark(context)

    // --- ER PRIMARY ---
    val eerprimary: Color @Composable get() = DesignEngineController.eerprimary(isSystemInDarkTheme())
    val eerprimaryLight: Color @Composable get() = DesignEngineController.eerprimaryLight()
    val eerprimaryDark: Color @Composable get() = DesignEngineController.eerprimaryDark()
    val eferprimary: Color @Composable get() = DesignEngineController.eferprimary(isSystemInDarkTheme())
    val eferprimaryLight: Color @Composable get() = DesignEngineController.eferprimaryLight()
    val eferprimaryDark: Color @Composable get() = DesignEngineController.eferprimaryDark()
    @Composable fun ewerprimary(context: Context): Color = DesignEngineController.ewerprimary(context, isSystemInDarkTheme())
    @Composable fun ewerprimaryLight(context: Context): Color = DesignEngineController.ewerprimaryLight(context)
    @Composable fun ewerprimaryDark(context: Context): Color = DesignEngineController.ewerprimaryDark(context)

    // --- ER ON PRIMARY ---
    val eeronprimary: Color @Composable get() = DesignEngineController.eeronprimary(isSystemInDarkTheme())
    val eeronprimaryLight: Color @Composable get() = DesignEngineController.eeronprimaryLight()
    val eeronprimaryDark: Color @Composable get() = DesignEngineController.eeronprimaryDark()
    val eferonprimary: Color @Composable get() = DesignEngineController.eferonprimary(isSystemInDarkTheme())
    val eferonprimaryLight: Color @Composable get() = DesignEngineController.eferonprimaryLight()
    val eferonprimaryDark: Color @Composable get() = DesignEngineController.eferonprimaryDark()
    @Composable fun eweronprimary(context: Context): Color = DesignEngineController.eweronprimary(context, isSystemInDarkTheme())
    @Composable fun eweronprimaryLight(context: Context): Color = DesignEngineController.eweronprimaryLight(context)
    @Composable fun eweronprimaryDark(context: Context): Color = DesignEngineController.eweronprimaryDark(context)

    // --- ER PRIMARY CONTAINER ---
    val eerprimarycontainer: Color @Composable get() = DesignEngineController.eerprimarycontainer(isSystemInDarkTheme())
    val eerprimarycontainerLight: Color @Composable get() = DesignEngineController.eerprimarycontainerLight()
    val eerprimarycontainerDark: Color @Composable get() = DesignEngineController.eerprimarycontainerDark()
    val eferprimarycontainer: Color @Composable get() = DesignEngineController.eferprimarycontainer(isSystemInDarkTheme())
    val eferprimarycontainerLight: Color @Composable get() = DesignEngineController.eferprimarycontainerLight()
    val eferprimarycontainerDark: Color @Composable get() = DesignEngineController.eferprimarycontainerDark()
    @Composable fun ewerprimarycontainer(context: Context): Color = DesignEngineController.ewerprimarycontainer(context, isSystemInDarkTheme())
    @Composable fun ewerprimarycontainerLight(context: Context): Color = DesignEngineController.ewerprimarycontainerLight(context)
    @Composable fun ewerprimarycontainerDark(context: Context): Color = DesignEngineController.ewerprimarycontainerDark(context)

    // --- ER ON PRIMARY CONTAINER ---
    val eeronprimarycontainer: Color @Composable get() = DesignEngineController.eeronprimarycontainer(isSystemInDarkTheme())
    val eeronprimarycontainerLight: Color @Composable get() = DesignEngineController.eeronprimarycontainerLight()
    val eeronprimarycontainerDark: Color @Composable get() = DesignEngineController.eeronprimarycontainerDark()
    val eferonprimarycontainer: Color @Composable get() = DesignEngineController.eferonprimarycontainer(isSystemInDarkTheme())
    val eferonprimarycontainerLight: Color @Composable get() = DesignEngineController.eferonprimarycontainerLight()
    val eferonprimarycontainerDark: Color @Composable get() = DesignEngineController.eferonprimarycontainerDark()
    @Composable fun eweronprimarycontainer(context: Context): Color = DesignEngineController.eweronprimarycontainer(context, isSystemInDarkTheme())
    @Composable fun eweronprimarycontainerLight(context: Context): Color = DesignEngineController.eweronprimarycontainerLight(context)
    @Composable fun eweronprimarycontainerDark(context: Context): Color = DesignEngineController.eweronprimarycontainerDark(context)
}
